// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as schema$0 from "../../../../ankit-lilly/nqcli/internal/schema/models.js";

declare module "/wails/runtime.js" {
    namespace Events {
        interface CustomEvents {
            "schema:update": schema$0.Event;
        }
    }
}
