// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Attribute {
    "name": string;
    "dataType": string;
}

export interface Edge {
    "type": string;
    "attributes": Attribute[] | null;
    "total"?: number | null;
}

export interface EdgeConnection {
    "sourceVertexType": string;
    "edgeType": string;
    "targetVertexType": string;
}

export interface Event {
    "type": string;
    "key": string;
    "status": Status;
    "phase"?: string;
    "completed"?: number;
    "total"?: number;
    "error"?: string;
}

export interface Snapshot {
    "totalVertices"?: number | null;
    "vertices": Vertex[] | null;
    "totalEdges"?: number | null;
    "edges": Edge[] | null;
    "edgeConnections": EdgeConnection[] | null;
    "status": Status;
    "phase"?: string;
    "completed"?: number;
    "total"?: number;
    "error"?: string;
    "lastUpdate"?: string | null;
}

export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusEmpty = "empty",
    StatusRunning = "running",
    StatusReady = "ready",
    StatusFailed = "failed",
};

export interface Vertex {
    "type": string;
    "attributes": Attribute[] | null;
    "total"?: number | null;
}
