// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel currently active requests without discarding the application lifecycle context.
 */
export function CancelQueries(): $CancellablePromise<void> {
    return $Call.ByName("github.com/ankit-lilly/nqcli/internal/desktop.DesktopService.CancelQueries");
}

export function ExecuteGraphQuery(req: $models.QueryRequest): $CancellablePromise<$models.GraphResponse> {
    return $Call.ByName("github.com/ankit-lilly/nqcli/internal/desktop.DesktopService.ExecuteGraphQuery", req);
}

export function ExecuteQuery(req: $models.QueryRequest): $CancellablePromise<$models.QueryResponse> {
    return $Call.ByName("github.com/ankit-lilly/nqcli/internal/desktop.DesktopService.ExecuteQuery", req);
}

export function ExpandVertex(req: $models.ExpandVertexRequest): $CancellablePromise<$models.GraphResponse> {
    return $Call.ByName("github.com/ankit-lilly/nqcli/internal/desktop.DesktopService.ExpandVertex", req);
}

export function GetProfile(): $CancellablePromise<$models.ProfileInfo> {
    return $Call.ByName("github.com/ankit-lilly/nqcli/internal/desktop.DesktopService.GetProfile");
}

export function GetSoA(req: $models.SoASelection): $CancellablePromise<$models.DataResponse> {
    return $Call.ByName("github.com/ankit-lilly/nqcli/internal/desktop.DesktopService.GetSoA", req);
}

export function GetVertexProperties(req: $models.VertexPropsRequest): $CancellablePromise<$models.VertexPropsResponse> {
    return $Call.ByName("github.com/ankit-lilly/nqcli/internal/desktop.DesktopService.GetVertexProperties", req);
}

export function ListStudies(req: $models.StudySearch): $CancellablePromise<$models.DataResponse> {
    return $Call.ByName("github.com/ankit-lilly/nqcli/internal/desktop.DesktopService.ListStudies", req);
}

export function ListVersions(req: $models.StudySelection): $CancellablePromise<$models.DataResponse> {
    return $Call.ByName("github.com/ankit-lilly/nqcli/internal/desktop.DesktopService.ListVersions", req);
}

export function SwitchProfile(req: $models.ProfileRequest): $CancellablePromise<$models.ProfileResponse> {
    return $Call.ByName("github.com/ankit-lilly/nqcli/internal/desktop.DesktopService.SwitchProfile", req);
}
