// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as schema$0 from "../schema/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel currently active requests without discarding the application lifecycle context.
 */
export function CancelQueries(): $CancellablePromise<void> {
    return $Call.ByName("github.com/ankit-lilly/nqcli/internal/desktop.DesktopService.CancelQueries");
}

export function ExecuteGraphQuery(req: $models.QueryRequest): $CancellablePromise<$models.GraphResponse> {
    return $Call.ByName("github.com/ankit-lilly/nqcli/internal/desktop.DesktopService.ExecuteGraphQuery", req);
}

export function ExecuteQuery(req: $models.QueryRequest): $CancellablePromise<$models.QueryResponse> {
    return $Call.ByName("github.com/ankit-lilly/nqcli/internal/desktop.DesktopService.ExecuteQuery", req);
}

export function ExpandVertex(req: $models.ExpandVertexRequest): $CancellablePromise<$models.GraphResponse> {
    return $Call.ByName("github.com/ankit-lilly/nqcli/internal/desktop.DesktopService.ExpandVertex", req);
}

export function GetProfile(): $CancellablePromise<$models.ProfileInfo> {
    return $Call.ByName("github.com/ankit-lilly/nqcli/internal/desktop.DesktopService.GetProfile");
}

/**
 * GetSchema returns cached schema data immediately and revalidates it in the
 * background when absent, stale, or explicitly refreshed.
 */
export function GetSchema(req: $models.SchemaRequest): $CancellablePromise<schema$0.Snapshot> {
    return $Call.ByName("github.com/ankit-lilly/nqcli/internal/desktop.DesktopService.GetSchema", req);
}

export function GetVertexProperties(req: $models.VertexPropsRequest): $CancellablePromise<$models.VertexPropsResponse> {
    return $Call.ByName("github.com/ankit-lilly/nqcli/internal/desktop.DesktopService.GetVertexProperties", req);
}

export function SwitchProfile(req: $models.ProfileRequest): $CancellablePromise<$models.ProfileResponse> {
    return $Call.ByName("github.com/ankit-lilly/nqcli/internal/desktop.DesktopService.SwitchProfile", req);
}
