// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as DesktopService from "./desktopservice.js";
export {
    DesktopService
};

export type {
    DataResponse,
    ExpandVertexRequest,
    GraphElement,
    GraphResponse,
    ProfileInfo,
    ProfileRequest,
    ProfileResponse,
    QueryRequest,
    QueryResponse,
    SoASelection,
    StudySearch,
    StudySelection,
    VertexPropsRequest,
    VertexPropsResponse
} from "./models.js";
