// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DataResponse {
    "data": any;
    "error"?: string;
    "warning"?: string;
}

export interface ExpandVertexRequest {
    "id": string;
    "type": string;
    "direction": string;
    "relationship": string;
    "neighborLabel": string;
    "limit": number;
    "excludedVertexIds": string[] | null;
}

export interface GraphElement {
    "group": string;
    "data": { [_ in string]?: any } | null;
}

export interface GraphResponse {
    "warning"?: string;
    "elements": GraphElement[] | null;
    "error"?: string;
}

export interface ProfileInfo {
    "profile": string;
    "env": string;
    "profiles": string[] | null;
}

export interface ProfileRequest {
    "profile": string;
}

export interface ProfileResponse {
    "profile": string;
    "env": string;
    "error"?: string;
}

export interface QueryRequest {
    "query": string;
    "type": string;
    "serializer": string;
}

export interface QueryResponse {
    "processed": string;
    "raw"?: string;
    "error"?: string;
}

export interface SoASelection {
    "versionId": string;
    "designId": string;
}

export interface StudySearch {
    "search": string;
}

export interface StudySelection {
    "studyId": string;
}

export interface VertexPropsRequest {
    "id": string;
}

export interface VertexPropsResponse {
    "properties": { [_ in string]?: any } | null;
    "error"?: string;
}
