// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ExpandVertexRequest {
    "id": string;
    "type": string;
    "direction": string;
    "relationship": string;
    "neighborLabel": string;
    "limit": number;
    "excludedVertexIds": string[] | null;
}

export interface GraphElement {
    "group": string;
    "data": { [_ in string]?: any } | null;
}

export interface GraphResponse {
    "warning"?: string;
    "elements": GraphElement[] | null;
    "json"?: string;
    "error"?: string;
}

export interface NeighborOption {
    "label": string;
    "count": number;
}

export interface NeighborSummaryRequest {
    "id": string;
    "type": string;
    "direction": string;
}

export interface NeighborSummaryResponse {
    "nodes": NeighborOption[] | null;
    "relationships": NeighborOption[] | null;
    "error"?: string;
}

export interface ProfileInfo {
    "profile": string;
    "env": string;
    "profiles": string[] | null;
}

export interface ProfileRequest {
    "profile": string;
}

export interface ProfileResponse {
    "profile": string;
    "env": string;
    "error"?: string;
}

export interface QueryRequest {
    "query": string;
    "type": string;
    "serializer": string;
}

export interface QueryResponse {
    "processed": string;
    "raw"?: string;
    "error"?: string;
}

export interface SchemaRequest {
    "refresh": boolean;
}

export interface VertexPropsRequest {
    "id": string;
}

export interface VertexPropsResponse {
    "properties": { [_ in string]?: any } | null;
    "error"?: string;
}
